### ISSUE TITLE
钱箱指令

### ISSUE THREAD

**Issue by tossp** [baka397/chn-escpos#1]
钱箱默认指令用`\x1B\x70\x00\xFF\xFF`是不是更通用一些？
现在的`\x1b\x70\x07`我测试时失败的

我测试时POS打印机是STRP的SP-POS58

**Comment by baka397** [comment]
https://reference.epson-biz.com/modules/ref_escpos/index.php?content_id=195
确实是,我换成epson的通用标准

**Comment by tossp** [comment]
更新很快啊，谢谢

**Comment by dondallas** [comment]
/Users/wangxiaohui/Documents/my_project/database/dayin/node_modules/chn-escpos/lib/printer.js:37
            this._queue.concat(iconv.encode(text, 'GBK'));
                       ^

TypeError: Cannot read property 'concat' of undefined
    at Object.text (/Users/wangxiaohui/Documents/my_project/database/dayin/node_modules/chn-escpos/lib/printer.js:37:24)
    at Object.<anonymous> (/Users/wangxiaohui/Documents/my_project/database/dayin/index.js:21:10)
    at Object.printer (/Users/wangxiaohui/Documents/my_project/database/dayin/node_modules/chn-escpos/lib/printer.js:19:32)
    at Object.<anonymous> (/Users/wangxiaohui/Documents/my_project/database/dayin/index.js:18:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
